### PR TITLE
Fix TypeError: propagate_pool_optimization() got an unexpected keywor…

### PR DESCRIPTION
**Pull request by dmcg**
…d argument

### CODE REVIEW

**Comment by gjoseph92** [comment]
What was the unexpected keyword argument? What caused this to happen?

**Comment by dmcg** [comment]
From memory, when I called `compute(workers='metoffice-0')` within the context manager the workers argument was being passed to propagate_pool_optimization by some function that called it by reference

**Comment by dmcg** [comment]
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File <timed exec>:13, in <module>

Input In [8], in show_all_workers()
      9 def show_all_workers():
---> 10     my_org().compute(workers='metoffice-0')
     11     my_org().compute(workers='metoffice-1')
     12     my_org().compute(workers='metoffice-2')

File ~/miniconda3/envs/irisxarray/lib/python3.10/site-packages/dask/base.py:290, in DaskMethodsMixin.compute(self, **kwargs)
    266 def compute(self, **kwargs):
    267     """Compute this dask collection
    268 
    269     This turns a lazy Dask collection into its in-memory equivalent.
   (...)
    288     dask.base.compute
    289     """
--> 290     (result,) = compute(self, traverse=False, **kwargs)
    291     return result

File ~/miniconda3/envs/irisxarray/lib/python3.10/site-packages/dask/base.py:567, in compute(traverse, optimize_graph, scheduler, get, *args, **kwargs)
    559     return args
    561 schedule = get_scheduler(
    562     scheduler=scheduler,
    563     collections=collections,
    564     get=get,
    565 )
--> 567 dsk = collections_to_dsk(collections, optimize_graph, **kwargs)
    568 keys, postcomputes = [], []
    569 for x in collections:

File ~/miniconda3/envs/irisxarray/lib/python3.10/site-packages/dask/base.py:345, in collections_to_dsk(collections, optimize_graph, optimizations, **kwargs)
    342     dsk = opt(dsk, keys, **kwargs)
    344     for opt_inner in optimizations:
--> 345         dsk = opt_inner(dsk, keys, **kwargs)
    347     graphs.append(dsk)
    349 # Merge all graphs

TypeError: propagate_pool_optimization() got an unexpected keyword argument 'workers'
```

**Comment by gjoseph92** [comment]
Got it, thanks. Guess the docs here are wrong https://docs.dask.org/en/stable/optimize.html#customizing-optimization

**Pull request merged**
